--Shana Szanzer


	SELECT VENDORCONTACTFNAME, VENDORCONTACTLNAME, VENDORNAME
	FROM VENDORS ven
	ORDER BY VENDORCONTACTLNAME, VENDORCONTACTFNAME;

	SELECT InvoiceNumber AS NUMBER, INVOICETOTAL AS TOTAL, 
	PAYMENTTOTAL + CREDITTOTAL AS CREDITS, INVOICETOTAL - (PAYMENTTOTAL + CREDITTOTAL) AS BALANCE
	FROM INVOICES inv


	SELECT  VENDORCONTACTLNAME + ', ' + VENDORCONTACTFNAME AS FullName
	FROM VENDORS ven
	ORDER BY VENDORCONTACTLNAME + ',' + VENDORCONTACTFNAME;



	